version: 2.1
orbs:
  buildpulse: workshop64/buildpulse@0.3
jobs:
  build:
    docker:
      - image: circleci/node:12.13-browsers
    steps:
      - checkout
      - buildpulse/setup # Set up BuildPulse connection *before* running the test suite
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - buildpulse/upload:
          path: /tmp/test-results
          account-id: 68192324 # Replace this value with your BuildPulse account ID
          repository-id: 239299701 # Replace this value with your BuildPulse repository ID
